# Generated by Django 5.2 on 2025-04-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookmark_delete_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='created_at',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='name',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='time_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default='Smth', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='favicon',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table=None,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='main.group'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('time_deleted__isnull', True)), fields=('url',), name='URL_UNIQUE_IF_NOT_DELETED'),
        ),
    ]
